riding-rails-the-ror-tutorial/hello-app-step-2/config/routes.rb
# -*- coding:utf-8 -*-

Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html

  # リダイレクトさせる
  # 別のコントローラで表示させる場合は、次のようにする。
  #   root to: "welcome#index"
  root to: redirect("/articles/")
end

riding-rails-the-ror-tutorial/hello-app-step-2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

riding-rails-the-ror-tutorial/hello-app-step-2/app/models/article.rb
# -*- coding:utf-8 -*-

# 記事
class Article < ApplicationRecord
  # 検証: 列は複数並べてもよい.
  validates :title, presence:true

  # カスタム検証 & 値の整え
  validate :my_validation
  
  # Callback として, `before_save`, `before_validation` などがある.
  # Validation のほうが `before_save()` より先に実行される. ので、値の更新は
  # `validate()` のなかに入れないといけない.
  #before_save :normalize_text

private
  # for `validate`.
  def my_validation
    self.title = title.unicode_normalize :nfkc # 試しに
    self.body = body.unicode_normalize :nfc
    
    if title == "NG"
      errors[:title] << "値がNG!"
    end
  end

end

riding-rails-the-ror-tutorial/hello-app-step-2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

riding-rails-the-ror-tutorial/hello-app-step-2/app/controllers/articles_controller.rb
# -*- coding:utf-8 -*-

# 記事コントローラ
class ArticlesController < ApplicationController
  # 各アクション (メソッド) の前に呼び出される.
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    begin
      @article.save!
    rescue ActiveRecord::RecordInvalid
      render :new, status: :unprocessable_entity
      return
    end
    redirect_to @article, notice: "Article was successfully created." 
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    begin
      @article.update!(article_params)
    rescue ActiveRecord::RecordInvalid
      render :edit, status: :unprocessable_entity
      return
    end

    redirect_to @article, notice: "Article was successfully updated." 
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Article was successfully destroyed." 
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

riding-rails-the-ror-tutorial/hello-app-step-2/app/helpers/application_helper.rb
module ApplicationHelper
end

riding-rails-the-ror-tutorial/hello-app-step-2/app/helpers/articles_helper.rb
module ArticlesHelper
end

riding-rails-the-ror-tutorial/hello-app-step-2/app/views/articles/_form.html.erb
<% # Rails5 から form_with. 以前は form_for / form_tag だった.
   # url: オプションを指定 (以前の form_tag), or
   # model: オプションを指定 (以前の form_for).
  %>

<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>  <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :body %>   <%= form.text_area :body %>
  </div>

  <div class="actions">
<% # new (create) or edit (update) 判定
  %>
    <%= link_to 'キャンセル', article.persisted? ? @article : articles_path %>
    <%= form.submit %>
  </div>
<% end %>

riding-rails-the-ror-tutorial/hello-app-step-2/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

riding-rails-the-ror-tutorial/hello-app-step-2/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
<% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= link_to 'Show', article %></td>
      <td><%= link_to 'Destroy', article, method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
  </tbody>
</table>

<p><%= link_to 'New Article...', new_article_path %>

riding-rails-the-ror-tutorial/hello-app-step-2/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

riding-rails-the-ror-tutorial/hello-app-step-2/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit...', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>