admin-sample/config/routes.rb
Rails.application.routes.draw do

  mount Motor::Admin => '/motor_admin'
  #mount Avo::Engine, at: Avo.configuration.root_path

  # バリエーション
  resources :product_groups

  # 品目, セット品 & 構成品
  resources :products do
    member do
      post :new_child, to: "prod_structures#new"
      post :approval_request
      post :new_revision
      post :add_attr
      get :edit_attrs
      post :update_attrs
    end
    resources :packages
  end

  resources :prod_structures, except:[:new]
  
  # 軸
  resources :prod_attrs do
    member do
      post :new_enum, to: "attr_enum_values#new"
    end
    resources :attr_enum_values, except:[:new]
  end

  # 販売
  resources :sales_pages
  
  resources :sales_skus

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root :to => redirect("/product_groups/")
end

admin-sample/app/models/product.rb
# 物体 (品目) revision
class Product < ApplicationRecord
  #SINGLE = 1; BUNDLE_SET = 2; COMPONENT = 3

  STATUS_STR = {
    0  => "draft",
    10 => "confirming",
    20 => "approved" }
  
  belongs_to :product_code
  validates :revision_no, presence: true
  
  # (attr - value) pairs 
  has_many :prod_attr_values
  
  # if BUNDLE_SET, not use
  has_many :packages
  
  #validates :cmpt_type, presence: true
  
  validates :name, presence: true

  before_validation :check_fields

private
  def check_fields
    # 0 = draft, 10 = inflow, 20 = approved
    self.appro_status = 0 if !appro_status
    self.revision_no = 0  if !revision_no
  end
  
end

admin-sample/app/controllers/products_controller.rb
# 品目
class ProductsController < ApplicationController
  before_action :set_sku,
        only: %i[ show edit update destroy approval_request add_attr edit_attrs update_attrs new_revision]

  # GET /skus or /skus.json
  def index
    @skus = ProductCode.latest_products(true)
  end

  # GET /skus/1 or /skus/1.json
  def show
  end

  # POST
  def approval_request
    @sku.appro_status = 20
    @sku.save!
    redirect_to({action:"show", id:@sku})
  end

  # POST
  def new_revision
    new_sku = @sku.dup # force new_record
    new_sku.revision_no = @sku.revision_no + 1
    new_sku.appro_status = 0  # draft

    begin
      ActiveRecord::Base.transaction do
        new_sku.save!
        @sku.prod_attr_values.each do |a|
          new_a = a.dup
          new_a.product_id = new_sku.id
          new_a.save!
        end
        @sku.packages.each do |pack|
          new_pack = pack.dup
          new_pack.product_id = new_sku.id
          new_pack.save!
        end
        
        redirect_to product_url(new_sku), notice: "Sku was successfully created."
      end
    rescue ActiveRecord::RecordInvalid => e
      render :show, status: :unprocessable_entity 
    end
  end

  
  # POST
  def add_attr
    attr_value = ProdAttrValue.new product_id: @sku.id, prod_attr_id: params[:prod_attr_id], raw_value: ""
    attr_value.save!
    render turbo_stream: turbo_stream.prepend("attributes", partial:"attr_value", locals:{attr_value:attr_value})
  end
  
  # GET /skus/new
  def new
    @sku = Product.new
    @prod_var_id = nil
    @sku_code = ProductCode.new
  end

  # GET /skus/1/edit
  def edit
    @prod_var_id = @sku.product_code.prod_variation &.id
  end

  # POST /skus or /skus.json
  def create
    @sku_code = ProductCode.new(id: params[:product_code])
    @prod_var_id = params[:prod_var_id]
    @sku_code.prod_variation_id = @prod_var_id
    @sku = Product.new(sku_params)

    begin
      ActiveRecord::Base.transaction do
        @sku_code.save!
        @sku.product_code_id = @sku_code.id
        @sku.save!
        redirect_to product_url(@sku), notice: "Sku was successfully created."
      end
    rescue ActiveRecord::RecordInvalid => e
      render :new, status: :unprocessable_entity 
    end
  end

  def edit_attrs
    
  end

  def update_attrs
  end
  
  
  # PATCH/PUT /skus/1 or /skus/1.json
  def update
    @prod_var_id = params[:prod_var_id]
    @sku.attributes = sku_params
    @sku.product_code.prod_variation_id = @prod_var_id

    begin
      ActiveRecord::Base.transaction do
        @sku.product_code.save!
        @sku.save!
        redirect_to product_url(@sku), notice: "Sku was successfully updated."
      end
    rescue ActiveRecord::RecordInvalid => e
      render :edit, status: :unprocessable_entity 
    end
  end

  
  # DELETE /skus/1 or /skus/1.json
  def destroy
    begin
      ActiveRecord::Base.transaction do
        @sku.destroy!
        if @sku.product_code.revisions.size == 0
          @sku.product_code.destroy!
        end
        redirect_to products_url, notice: "Sku was successfully destroyed." 
      end
    rescue
      raise
    end
  end

  
private
  # Use callbacks to share common setup or constraints between actions.
  def set_sku
    @sku = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sku_params
    params.require(:product).permit(:cmpt_type, :name )
  end
end

admin-sample/app/views/products/_attr_value.html.erb
  <div class="columns" id="<%= dom_id attr_value %>" >
    <div class="column"><%= attr_value.prod_attr.name %></div>
    <div class="column"><%= attr_value.value %></div>
  </div>

admin-sample/app/views/products/_form.html.erb
  <%= error_messages_for form.object %>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label for="product_code" class="label">Product Code:</label>
  </div>
  <div class="field-body">
    <div class="field is-narrow"><%= @sku.product_code ? @sku.product_code.id : "" %></div>
  </div>
</div>
  
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label for="prod_var_id" class="label">Product Group:</label>
  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
	<%= select_tag( :prod_var_id,
                options_from_collection_for_select(ProdVariation.all, :id, :name,
                                 @prod_var_id),
                :include_blank => true) %>
      </div>
    </div>
  </div>
</div>
  
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :name, "Item Name:", class:"label" %>
  </div>
  <div class="field-body">
    <div class="field ">
      <div class="control">
	<%= form.text_field :name, class:"input" %>
      </div>
    </div>
  </div>
</div>

admin-sample/app/views/products/_sku.html.erb
<tr id="<%= dom_id sku %>">
  <td><%= sku.product_code.id %>
  <td><%= sku.name %>
  <td>
<% sku.product_code.children.each do |child| %>
  <%= child.id %> <%= child.latest_product(true).name %> <br />   
<% end %>    
  <td><%= link_to "Show", {action:"show", id:sku} %>
</tr>

admin-sample/app/views/products/edit.html.erb
<% content_for(:title) {"Editing Item"} %>

<%= form_with(model: @sku, url:{action:"update", id:@sku}) do |form| %>
  <%= render partial:"form", locals:{form:form, sku: @sku} %>


  <div>
    <%= link_to "Cancel", {action:"show", id:@sku} %> |
    <%= form.submit %>
  </div>
<% end %>

admin-sample/app/views/products/edit_attrs.html.erb
<% content_for(:title) { "Edit Attributes" } %>

<p><b>Product:</b> <%= @sku.name %>

<%= form_with(model:@sku.prod_attr_values, url:{action:"update_attrs", id:@sku}) do |form| %>
  
<table class="table">
<% @sku.prod_attr_values.each do |pair| %>
  <tr><th><%= pair.prod_attr.name %>
    <td>
<% case pair.prod_attr.attr_type
   when ProdAttr::TYPE_LENGTH %>
      <%= form.text_field pair.id, value: pair.raw_value %>
<% when ProdAttr::TYPE_COLOUR %>
      <%= form.select  pair.id,
                    options_from_collection_for_select(pair.prod_attr.enum_values, :id, :value , pair.enum_value_id) %>
<% end %>
    </td>      
<% end %>
</table>

  <%= link_to "Cancel", @sku %>
  <%= form.submit "Update (not yet)" %>
<% end %>

admin-sample/app/views/products/index.html.erb
<% content_for(:title) { "Product Structure" } %>


<table id="skus" class="table">
  <tr><th>Prod.Code
    <th>Name
    <th>Child items
  <% @skus.each do |sku| %>
    <%= render partial:"sku", locals:{sku:sku} %>
  <% end %>
</table>

<p><%= link_to "New Item...", new_product_path %>

admin-sample/app/views/products/new.html.erb
<% content_for(:title) { "New Item" } %>

<%= form_with(model: @sku, url:{action:"create"}) do |form| %>
  <%= render partial:"form", locals:{form:form, sku: @sku} %>

  <div>
    <%= link_to "Cancel", products_path %>
    <%= form.submit %>
  </div>
<% end %>

admin-sample/app/views/products/show.html.erb
<% content_for(:title) { "Item: " + @sku.name + ", rev #{@sku.revision_no}" }
   @crumbs = [
     [{action:"index"}, "Product Structure"] ]
  %>

<div class="columns">
  <div class="column">
    Revisions:
<% @sku.product_code.revisions.each do |rev| %>
  <%= link_to rev.revision_no, {action:"show", id:rev} %>
<% end %>
  </div>

  <div class="column">
<% if @sku.appro_status < 20 %>
  <%= button_to "Approve", {action:"approval_request", id:@sku}, class:"button", form:{class:"is-inline-block"} %>
<% end %>

  <%= button_to "New Revision!", {action:"new_revision", id:@sku}, class:"button", form:{class:"is-inline-block"} %>
  </div>
</div>


<section class="section">
<h2 class="title is-4" >Basic Information</h2>

<table class="table">
  <tr><th>Product Code: <td><%= @sku.product_code.id %>
  <tr><th>Name: <td><%= @sku.name %>
  <tr><th>Revision: <td><%= @sku.revision_no %>
  <tr><th>Status:
    <td><%= Product::STATUS_STR[@sku.appro_status] %>
  <tr><th>Updated at: <td><%= @sku.updated_at %>	      

  <tr><th>Product Group:
    <td>	    
  <% if (var = @sku.product_code.prod_variation) != nil %>
    <%= link_to var.name, {controller:"product_groups", action:"show", id:var} %>
  <% end %>
</table>              

<div>
  <%= link_to "Edit this Item...", edit_product_path(@sku) %> |
  <%= button_to "Destroy this Item", {action:"destroy", id:@sku}, method: :delete,
                class:"button", form:{class:"is-inline-block", data:{turbo_confirm:"Are you sure?"}}  %>
</div>
</section>


<p>複数梱包と構成品を混同しないように。
<p>セット販売は、ここではなく、販売SKU の画面で設定すること。

<section class="section">
  <div class="columns">
    <div class="column">
<nav class="panel">
  <h3 class="panel-heading">Parent Items</h3>
  <div class="panel-block">
<% @sku.product_code.parent_hierarchies.each do |pa| %>
<%   parent_code = pa.parent
     parent = parent_code.latest_product(true) %>
      <p><%= link_to parent.name, {controller:"products", action:"show", id:parent} %>
        <%= pa.qty %>
	<%= Product::STATUS_STR[parent.appro_status] %>
<% end %>
  </div>
</nav>  
    </div>  <!-- /.column -->


    <div class="column">
<nav class="panel">
  <h3 class="panel-heading">Child Items</h3>
  <div class="panel-block">  
      <div id="child_items">
<% @sku.product_code.child_hierarchies.each do |ch| %>
        <%= render ch %>	
<% end %>
      </div>	
  </div>
  <div class="panel-block">
        <%= button_to "Add...", new_child_product_path(), class:"button" %>
  </div>
</nav>
    </div> <!-- /.column -->
  </div>
</section>



<section class="section">
<h2 class="title is-4">Packages</h2>

<table class="table">
  <tr><th>QPC <th>Case No.  <th>W (cm) <th>D  <th>H  <th>Gross Weight (kg)
<% @sku.packages.order(:qpc).each do |package| %>
  <tr><td><%= package.qpc %>
    <td><%= package.case_no %>
    <td><%= package.size_width %>	  
    <td><%= package.size_depth %>	  
    <td><%= package.size_height %>	  
    <td><%= package.gross_weight  %>
    <td><%= link_to "Edit...", edit_product_package_path(@sku, package) %>
<% end %>					
</table>

<p><%= link_to "New package...", new_product_package_path(@sku)  %>
</section>




<section class="section">
<h2 class="title is-4">Attributes</h2>

<p><%= link_to "Edit Attributes...", {action:"edit_attrs", id:@sku} %>
  
<div id="attributes">
<% @sku.prod_attr_values.each do |attr| %>
  <%= render partial:"attr_value", locals:{attr_value:attr} %>
<% end %>
</div>

<%= form_with(url:{action:"add_attr"}) do |form| %>
  <%= select_tag :prod_attr_id, options_from_collection_for_select(ProdAttr.all, :id, :name) %>
  <%= form.submit "Add", class:"button" %>
<% end %>
  
</section>