LoginSample-sorcery-1/config/routes.rb
# -*- coding:utf-8 -*-

Rails.application.routes.draw do
  # ユーザアカウント. 単数形リソース singleton resource を使う
  # 単数形リソースであってもデフォルトコントローラ名は複数形。
  # => controller: オプションでクラス名を指定する
  resource :account, only: [:show, :create, :edit, :update],
                     controller: 'account' do
    get    'sign_up'
    match  'sign_in', via:[:get, :post]
    delete 'sign_out'
  end

  # 顧客
  resources :customers

  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html

  root "welcome#index"
end

LoginSample-sorcery-1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

LoginSample-sorcery-1/app/models/customer.rb
class Customer < ApplicationRecord
end

LoginSample-sorcery-1/app/models/user.rb
# -*- coding:utf-8 -*-

# ユーザ
class User < ApplicationRecord
  # Sorcery core モジュール
  # この呼び出しにより, サブモジュールの include や, init_orm_hooks! など.
  authenticates_with_sorcery!

  validates :password, length: {minimum: 6},
                       if: -> { new_record? || changes[:crypted_password] }
  # ActiveRecord の機能。フィールド名は対象のフィールド名に _confirmation を加
  # えたものになる。
  validates :password, confirmation: true,
                       if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true,
                       if: -> { new_record? || changes[:crypted_password] }

  # メールアドレスで識別.
  validates :email, presence:true
  validates :email, uniqueness: true
end

LoginSample-sorcery-1/app/controllers/account_controller.rb
# -*- coding:utf-8 -*-

# ユーザアカウント
class AccountController < ApplicationController
  skip_before_action :require_login, only: %i[sign_up create sign_in]

  # GET /
  # 単数形リソースでは, index メソッドではなく show メソッド.
  def show
    @user = current_user
  end

  # GET /sign_up   -- new_user_registration
  def sign_up
    if current_user
      redirect_to sign_in_account_url
      return
    end
    @user = User.new
  end

  # POST /  -- user_registration
  def create
    @user = User.new user_params
    begin
      @user.save!  # 注意: ここで, @user.password がクリアされる
    rescue ActiveRecord::RecordInvalid
      render :sign_up, status: :unprocessable_entity
      return
    end

    # 流れでログインする.
    # login() は Sorcery::Controller module で定義される。
    u = login(@user.email, user_params[:password])
    raise "internal error" if !u
    redirect_to(account_url, notice: 'User created.')
  end


  # GET /edit
  def edit
    @user = current_user
  end

  # PUT /
  def update
    raise # TODO: impl.
  end


  # GET /sign_in   -- new_user_session
  # POST /sign_in  -- user_session
  def sign_in
    if request.get?
      @user = User.new
      return 
    end

    @user = User.new user_params
    @remember = params[:remember]

    # remember_me サブモジュールを組み込んだ場合, 第3引数で記憶させるか選ぶ
    # `auto_login()` メソッド内で, 単に真偽値で見ている
    # Trap: check_box の値をそのまま渡すと、常に真.
    if login(@user.email, @user.password,
             ActiveRecord::Type::Boolean.new.cast(@remember))
      redirect_back_or_to(account_url, notice: 'Login successful')
    else
      flash[:alert] = 'Login failed'
      render 'sign_in'
    end    
  end


  # DELETE /sign_out  -- destroy_user_session
  def sign_out
    # ここで forget_me! が必要では? (Web上の解説では書いているものもある)
    # -> 不要. 'before_logout' hook で forget_me! が登録されている.
    logout
    redirect_to '/', notice: 'Logged out!'
  end


private
  def user_params
    # AccountController では自分のデータしか更新させないので, :password をこの
    # 場所で permit() しても差し支えない.
    # permit() は重ねることはできない (許可を広げられない) ので、コントローラ内
    # で許可範囲を変えたいときは、それぞれのアクション内で permit() すること.
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

LoginSample-sorcery-1/app/controllers/application_controller.rb
# -*- coding:utf-8 -*-

# 各コントローラの基底クラス.
# - ActionController::Base クラスは Rails における web request のコア。
#   ActionController::Metal クラスから派生.
# - Metal は actionpack パッケージ, AbstractController::Base から派生.
class ApplicationController < ActionController::Base
  # ポカ避けのため, ログイン不要のアクションだけ skip_before_action する.
  before_action :require_login


private
  
  # 未ログインの状態で要ログインのページにアクセスした時に呼び出される
  def not_authenticated
    redirect_to sign_in_account_url
  end  
end

LoginSample-sorcery-1/app/controllers/customers_controller.rb
# -*- coding:utf-8 -*-

# 顧客情報
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @users = User.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.user_id = current_user.id
    
    if @customer.save
      redirect_to @customer, notice: "Customer was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: "Customer was successfully destroyed."
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def customer_params
    params.fetch(:customer, {})
  end
end

LoginSample-sorcery-1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login

  def index
  end
end

LoginSample-sorcery-1/app/helpers/application_helper.rb
# -*- coding:utf-8 -*-

# View から呼び出せるメソッド群.
module ApplicationHelper

  # エラーメッセージを表示します。
  # errors() は ActiveModel::Validations
  def error_messages_for model_obj
    if model_obj.respond_to?(:errors)
      render(partial: "layouts/error_messages", locals:{model_obj:model_obj})
    end
  end
end

LoginSample-sorcery-1/app/views/layouts/_error_messages.html.erb
<% # @param model_obj エラー表示の対象オブジェクト
  %>

<% if model_obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model_obj.errors.count, "error") %> prohibited this customer from being saved:</h2>

    <ul>
<% model_obj.errors.each do |error| %>
      <li><%= error.full_message %></li>
<% end %>
    </ul>
  </div>
<% end %>

LoginSample-sorcery-1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>LoginSample</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="/bootstrap5/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "application", defer: true %>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <div class="container-fluid" aria-label="Main navigation">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home</a>
        </li>
      </ul>
<% if current_user %>
      <span class="navbar-text"><%= current_user.email %></span>      
<% end %>      
      <ul class="navbar-nav">
<% if current_user %>
<!--
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_account_url, class: 'nav-link' %>
  -->
        <li class="nav-item">
          <%= link_to "Logout", sign_out_account_url,
                      method: :delete, class:'btn btn-sm btn-secondary nav-link' %>
        </li>
<% else %>
        <li class="nav-item">
          <%= link_to "Register", sign_up_account_url, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_account_url, class: 'btn btn-sm btn-success nav-link' %>
        </li>
<% end %>
      </ul>
    </div>
  </div>
</nav>

<% # flash[:notice], flash[:alert] は短縮表記もある. See ActionDispatch::Flash
   {notice: "alert alert-success",
    alert: "alert alert-danger"}.each do |key, klass|
     if (message = flash[key]) %>
<%= tag.div(class: klass + " alert-dismissible fade show", role:"alert") do %>
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
<% end %>
<%   end
   end %>


  <%= yield %>

  <script src="/bootstrap5/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>